Asite/Asite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^availabook/', include('availabook.urls', namespace='availabook')),
	url(r'^admin/', include(admin.site.urls))]
#url(r'^admin/', include(admin.site.urls))

Asite/availabook/urls.py
from django.conf.urls import url

from . import views

app_name = 'availabook'
print app_name
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/', views.login, name='login'),
    url(r'^fb_login/', views.fb_login, name='fb_login'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^home/', views.home, name='home'),
    url(r'^post_event/',views.post_event, name='post_event'),
    url(r'^get_fave/',views.get_fave,name='get_fave'),
    url(r'^profile/',views.profile,name='profile'),
    url(r'^upload/',views.upload,name='upload'),
    url(r'^info/',views.info,name='info'),
    url(r'^edit/',views.edit,name='edit'),
    url(r'^temp/',views.temp,name='temp'),
]

Asite/availabook/forms.py
from django import forms

class UploadFileForm(forms.Form):
    ''' form for upload file '''
    # name = forms.CharField(max_length=50)
    # pic = forms.ImageField()

Asite/availabook/views.py
import time
import uuid
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.core import serializers
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.models import User
from availabook.models import Users, Signup, Event, get_event_by_EId, get_event_list, put_event_into_db, get_recommended_event_list, get_user_by_email, get_user_info_from_eventlist, get_post_events_from_user,get_recommend_newversion
from availabook.recommendation import recommend_to_all,update_like_or_post_tag
from django.middleware import csrf
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.decorators.csrf import csrf_exempt
import sys
from boto3.session import Session
import os
import json
from django.http import JsonResponse
from forms import UploadFileForm
from boto3.session import Session
from boto.s3.connection import S3Connection
from boto.s3.key import Key
"""reload intepretor, add credential path"""
reload(sys)
sys.setdefaultencoding('UTF8')


"""import credentials from root/AppCreds"""
print "path: " + os.path.dirname(sys.path[0])
with open(os.path.dirname(sys.path[0])+ '/Asite' + '/availabook/AppCreds/AWSAcct.json','r') as AWSAcct:
    awsconf = json.loads(AWSAcct.read())
#setup the bucket
#conn = S3Connection('<aws access key>', '<aws secret key>')
conn = S3Connection(awsconf["aws_access_key_id"], awsconf["aws_secret_access_key"])
bucket = conn.get_bucket('image-availabook')




# Create your views here.
def index(request):
    ''' render the landing page'''
    for key in request.session.keys():
        del request.session[key]

    if request.user.is_authenticated():
        print "home"
        #event_list = get_recommend_newversion(request.user.username)
        #email_list, user_name_list, user_picture_list = get_user_info_from_eventlist(event_list)
        #zipped_list = zip(event_list, email_list, user_name_list, user_picture_list)
        return render(request, 'homepage.html',{'zipped_list': zipped_list, 'logedin': True})
    else:
        print "landing"
        return render(request, 'landing.html')


def home(request):
    print(request.user.username)
    event_list = get_recommend_newversion(request.user.username)
    email_list, user_name_list, user_picture_list = get_user_info_from_eventlist(event_list)
    zipped_list = zip(event_list, email_list, user_name_list, user_picture_list)
    if request.user.is_authenticated():
        fname = Users.get_user_info(request.user.username)['first_name']
        return render(request, 'homepage.html',{'zipped_list':zipped_list, 'logedin': True,'fname':fname})
    else:
        print "not authenticate"
        return render(request, 'homepage.html',{'zipped_list':zipped_list, 'logedin': False})


@csrf_exempt
def fb_login(request, onsuccess="/availabook/temp", onfail="/availabook/"):
    print "fb_login"
    user_id = str(request.POST.get("email"))
    pwd = str(request.POST.get("psw"))
    pwd_a = pwd
    firstname = request.POST.get("fn")
    lastname = request.POST.get("ln")
    age = request.POST.get("age")
    picture = request.POST.get("picture")
    print user_id, pwd, firstname, lastname, age, picture

    city = 'ny'
    zipcode = '10027'
    signup_handler = Signup(user_id, pwd, pwd_a, firstname, lastname, age, city, zipcode)
    signup_handler.add_picture(picture)

    user_db = Users(user_id, pwd)
    if user_db.verify_email() == False:
        print "account not exist"
        if not user_exists(user_id):
            user = User(username=user_id, email=user_id)
            user.set_password(pwd)
            user.save()
            authenticate(username=user_id, password=pwd)
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            auth_login(request, user)

            try:
                print "~~~~~~~~~"
                signup_handler.push_to_dynamodb()
                print "push success"
            except Exception as e:
                print (e)


            print str(request.user.username) + " is signed up and logged in: " + str(request.user.is_authenticated())
            return redirect(onsuccess)
        else:
            user=authenticate(username=user_id, password=pwd)
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            auth_login(request, user)
            print str(request.user.username) + " is signed up and logged in: " + str(request.user.is_authenticated())
            return redirect(onsuccess)
    else:
        print "dynamo has the user info", user_id, pwd
        user = authenticate(username=user_id, password=pwd)
        print user
        try:
            if user is not None:
                auth_login(request, user)
                print "redirecting"
                return redirect(onsuccess)
            else:
                print "user is none"
                return redirect(onfail)
        except Exception as e:
            print e
            return redirect(onfail)


@csrf_exempt
def login(request, onsuccess="/availabook/temp", onfail="/availabook/"):
    csrf_token = csrf.get_token(request)
    user_id = request.POST.get("id")
    pwd = request.POST.get("psw")
    print user_id, pwd, csrf_token

    user = authenticate(username=user_id, password=pwd)
    if user is not None:
        auth_login(request, user)
        print ("Current input user information is already existed in Django sqlite")
    else:
        print ("Current input user information is not existed in Django sqlite or the input password incorrect with that in Django sqlite!")
        return HttpResponse("Error")

    login_user = Users(user_id, pwd)
    if login_user.authen_user():
        login_user.authorize()
        print str(request.user.username) + " is logged in: " + str(request.user.is_authenticated())
        return redirect(onsuccess)
    else:
        print ("Current user information not exist in AWS Dynamodb or the input password is incorrect with that in AWS Dynamodb!")
        #return redirect(onfail)
        return HttpResponse("Error")


@csrf_exempt
def signup(request, onsuccess="/availabook/temp", onfail="/availabook/"):
    user_id = request.POST.get("email")
    pwd = request.POST.get("psw")
    pwd_a = request.POST.get("psw_a")
    firstname = request.POST.get("fn")
    lastname = request.POST.get("ln")
    age = request.POST.get("age")
    city = request.POST.get("city")
    zipcode = request.POST.get("zipcode")
    print user_id, pwd, pwd_a, firstname, lastname, age, city, zipcode

    signup_handler = Signup(user_id, pwd, pwd_a, firstname, lastname, age, city, zipcode)
    signup_handler.add_picture("https://s3.amazonaws.com/image-availabook/default")

    if pwd == pwd_a:
        if not user_exists(user_id):
            user = User(username=user_id, email=user_id)
            user.set_password(pwd)
            user.save()
            authenticate(username=user_id, password=pwd)
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            auth_login(request, user)
            print ("Successfully saving user information to Django sqlite.")
            try:
                signup_handler.push_to_dynamodb()
                print ("Successfully pushing user information to AWS Dynamodb.")
                print str(request.user.username) + " is signed up and logged in: " + str(request.user.is_authenticated())
                return redirect(onsuccess)
            except Exception as e:
                print (e)
                print ("Pushing user information to AWS Dynamodb failed! Please sign up again!")
                return HttpResponse("Error")
        else:
            user_db = Users(user_id, pwd)
            if user_db.verify_email() == False:
                print "Current user is already existed in Django sqlite, but not in AWS Dynamodb! Generally, sign up will fail. For debugging, maybe you should first delete this user from your django sqlite, clean the cache in browser and sign up again!"
                try:
                    signup_handler.push_to_dynamodb()
                    print ("Successfully pushing user information to AWS Dynamodb.")
                    if request.user.is_authenticated():
                        print str(request.user.username) + " is signed up and logged in: " + str(request.user.is_authenticated())
                        return redirect(onsuccess)
                    else:
                        print ("Sign up failed. Please debug following the instructions above!")
                        return HttpResponse("Error")
                except Exception as e:
                    print (e)
                    print ("Pushing user information to AWS Dynamodb failed! Please debug and sign up again!")
                    return HttpResponse("Error")
            else:
                print ("Current user is already existed in both Django sqlite and AWS Dynamodb! Please turn to log in first!")
                print ("If you still can't sign up and log in, for debugging, please delete this user from your django sqlite, clean the cache in browser and sign up again!")
                return HttpResponse("Error")
    else:
        print "Two input passwords inconsistent! Please sign up again!"
        return HttpResponse("Error")


def user_exists(username):
    ''' check if user exists'''
    user_count = User.objects.filter(username=username).count()
    if user_count == 0:
        return False
    return True


def logout(request):
    ''' logout and redirect'''
    if request.user.is_authenticated():
        print str(request.user.username) + " is logged out!"
        auth_logout(request)
    return redirect("/availabook/temp")


def temp(request):
    return render(request, 'homepage.html');


def profile(request):
    if request.user.is_authenticated():

Asite/availabook/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Availabook Social Network</title>

    <!-- Bootstrap core CSS -->
    {% load static %}
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
   <!--  <link href="css/bootstrap.css" rel="stylesheet"> -->

    <!-- Custom styles for this template -->
    {% load static %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% load static %}
    <link href="{% static 'fonts/css/font-awesome.css' %}" rel="stylesheet">
  </head>

  <body>

  <header>
    <div class="container">
      {% load static %}
      <img src="{% static 'img/logo.png' %}" class="logo" alt="">
      <form class="form-inline">
        <a href="{% url 'availabook:logout' %}" style="color:white">Logout</a> {% csrf_token %}
        <br>
      </form>

    </div>
  </header>

  <div id="signup" class="modal">
    <form method = "POST" class="modal-content animate" action = "{% url 'availabook:signup' %}"> {% csrf_token %}
    <div class="imgcontainer">
      <span onclick="document.getElementById('signup').style.display='none'" class="close" title="Close Modal">&times;</span>
    </div>
      <div class="container">
        <label><b>Email Address</b></label>
        <br>
        <input type="text" placeholder="Email Address" name="email" required>
        <br>
        <label><b>Password</b></label>
        <br>
        <input type="password" placeholder="Password" name="psw" required>
        <br>
        <label><b>Verify Password</b></label>
        <br>
        <input type="password" placeholder="Password" name="psw_a" required>
        <br>
        <label><b>First Name</b></label>
        <br>
        <input type="text" placeholder="First Name" name="fn" required>
        <br>
        <label><b>Last Name</b></label>
        <br>
        <input type="text" placeholder="Last Name" name="ln" required>
        <br>
        <label><b>Age</b></label>
        <br>
        <input type="text" placeholder="Integer" name="age" required>
        <br>
        <label><b>City</b></label>
        <br>
        <input type="text" placeholder="City" name="city" required>
        <br>
        <label><b>Zipcode</b></label>
        <br>
        <input type="text" placeholder="Zipcode" name="zipcode" required>
        <br>
        <button type="submit" style="margin-right:133px" class="subbtn">Sign up</button>
        <button type="button" onclick="document.getElementById('signup').style.display='none'" class="cancelbtn">Cancel</button>
      </div>

    </form>
  </div>


  <div id="signin" class="modal">
    <form method = "POST" class="modal-content animate" action = "{% url 'availabook:login' %}"> {% csrf_token %}
    <div class="imgcontainer">
      <span onclick="document.getElementById('signin').style.display='none'" class="close" title="Close Modal">&times;</span>
    </div>
      <div class="container">
        <label><b>Email Address</b></label>
        <br>
        <input type="text" placeholder="Email Address" name="id" required>
        <br>
        <label><b>Password</b></label>
        <br>
        <input type="password" placeholder="Password" name="psw" required>
        <br>
        <button type="submit" style="margin-right:137px" class="subbtn">Login</button>
        <button type="button" onclick="document.getElementById('signin').style.display='none'" class="cancelbtn">Cancel</button>
      </div>

    </form>
  </div>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            {% load static %}
            <li><a href="{% url 'availabook:profile' %}">Profile</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <section>
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Wall</h3>
              </div>
              <div class="panel-body">
                <form method="POST" action="{% url 'availabook:post_event' %}"> {% csrf_token %}
                  <div class="form-group">
                    <textarea class="form-control" name="content" placeholder="Write on the wall"></textarea>
                  </div>
                  <label>Date and Time: </label>
                  <input name="meeting" type="datetime-local" />
                  <button type="submit" class="btn btn-default">Submit</button>
                  <div class="pull-right">
                    <div class="btn-toolbar">
                      <button type="button" class="btn btn-default"><i class="fa fa-pencil"></i>Text</button>
                      <button type="button" class="btn btn-default"><i class="fa fa-file-image-o"></i>Image</button>
                      <button type="button" class="btn btn-default"><i class="fa fa-file-video-o"></i>Video</button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
            <ul>
            {% for event in event_list %}
            <li>
              <div class="panel panel-default post">
                <div class="panel-body">
                   <div class="row">
                     <div class="col-sm-2">
                     {% load static %}
                       <a href="profile.html" class="post-avatar thumbnail"><img src="{% static 'img/user.png' %}" alt=""><div class="text-center">DevUser1</div></a>
                       <div class="faves text-center">{{ event.fave_num }}-likes</div>
                     </div>
                     <div class="col-sm-10">
                       <div class="bubble">
                         <div class="pointer">
                           <p>{{ event.content }}</p>
                         </div>
                         <div class="pointer-border"></div>
                       </div>
                       <form method="POST" action="{% url 'availabook:get_fave' %}"> {% csrf_token %}
                        <p class="post-actions" ><button name="fave" type="submit" value={{event.EId}}>like</button>
                        </form>
                       <div class="comment-form">
                         <form class="form-inline"> {% csrf_token %}
                          <div class="form-group">
                            <input type="text" class="form-control" placeholder="enter comment">
                          </div>
                          <button type="submit" class="btn btn-default">Add</button>
                        </form>
                       </div>
                       <div class="clearfix"></div>

                       <div class="comments">
                         <div class="comment">
                         {% load static %}
                           <a href="#" class="comment-avatar pull-left"><img src="{% static 'img/user.png' %}" alt=""></a>
                           <div class="comment-text">
                             <p>I am just going to paste in a paragraph, then we will add another clearfix.</p>
                           </div>
                         </div>
                         <div class="clearfix"></div>
                         <div class="comment">
                           <a href="#" class="comment-avatar pull-left"><img src="{% static 'img/user.png' %}" alt=""></a>
                           <div class="comment-text">
                             <p>I am just going to paste in a paragraph, then we will add another clearfix.</p>
                           </div>
                         </div>
                         <div class="clearfix"></div>
                       </div>
                     </div>
                   </div>
                </div>
              </div>
              </li>
              {% endfor %}
              </ul>
    </section>

    <footer>
      <div class="container">
        <p>Availabook Copyright &copy, 2017</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    {% load static %}
    <script src= "{% static 'js/bootstrap.js' %}"></script>
    <script src= "{% static 'js/availabook.js' %}"></script>

<!--     <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script> -->
<!--     <script src="js/bootstrap.js"></script> -->
<!--     <script type="text/javascript" src="js/availabook.js"></script> -->

  </body>
</html>

Asite/availabook/templates/photos.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Availabook Social Network: Photos Page</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/style.css" rel="stylesheet">
    <link href="css/font-awesome.css" rel="stylesheet">
    <link href="css/ekko-lightbox.css" rel="stylesheet">

  </head>

  <body>

  <header>
    <div class="container">
      <img src="img/logo.png" class="logo" alt="">
      <form class="form-inline">
        <div class="form-group">
          <label class="sr-only" for="exampleInputEmail3">Email address</label>
          <input type="email" class="form-control" id="exampleInputEmail3" placeholder="Enter email">
        </div>
        <div class="form-group">
          <label class="sr-only" for="exampleInputPassword3">Password</label>
          <input type="password" class="form-control" id="exampleInputPassword3" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-default">Sign in</button><br>
        <div class="checkbox">
          <label>
            <input type="checkbox"> Remember me
          </label>
        </div>
      </form>
    </div>
  </header>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="index.html">Home</a></li>
<!--             <li><a href="members.html">Members</a></li>
            <li><a href="contact.html">Contact</a></li>
            <li><a href="groups.html">Groups</a></li>
            <li><a href="photos.html">Photos</a></li> -->
            <li><a href="profile.html">Profile</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <section>
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <h1 class="page-header">Photos</h1>
            <ul class="photos gallery-parent">
              <li><a href="img/sample1.jpg" data-hover="tooltip" data-placement="top" title="image" data-gallery="mygallery" data-parent=".gallery-parent" data-title="title" data-footer="this is a footer" data-toggle="lightbox"><img src="img/sample1.jpg" class="img-thumbnail" alt=""></a></li>
              <li><a href="img/sample2.jpg" data-hover="tooltip" data-placement="top" title="image" data-gallery="mygallery" data-parent=".gallery-parent" data-title="title" data-footer="this is a footer" data-toggle="lightbox"><img src="img/sample2.jpg" class="img-thumbnail" alt=""></a></li>
              <li><a href="img/sample3.jpg" data-hover="tooltip" data-placement="top" title="image" data-gallery="mygallery" data-parent=".gallery-parent" data-title="title" data-footer="this is a footer" data-toggle="lightbox"><img src="img/sample3.jpg" class="img-thumbnail" alt=""></a></li>
              <li><a href="img/sample4.jpg" data-hover="tooltip" data-placement="top" title="image" data-gallery="mygallery" data-parent=".gallery-parent" data-title="title" data-footer="this is a footer" data-toggle="lightbox"><img src="img/sample4.jpg" class="img-thumbnail" alt=""></a></li>
              <li><a href="img/sample5.jpg" data-hover="tooltip" data-placement="top" title="image" data-gallery="mygallery" data-parent=".gallery-parent" data-title="title" data-footer="this is a footer" data-toggle="lightbox"><img src="img/sample5.jpg" class="img-thumbnail" alt=""></a></li>
              <li><a href="img/sample6.jpg" data-hover="tooltip" data-placement="top" title="image" data-gallery="mygallery" data-parent=".gallery-parent" data-title="title" data-footer="this is a footer" data-toggle="lightbox"><img src="img/sample6.jpg" class="img-thumbnail" alt=""></a></li>
            </ul>
          </div>
          <div class="col-md-4">
            <div class="panel panel-default friends">
              <div class="panel-heading">
                <h3 class="panel-title">My Friends</h3>
              </div>
              <div class="panel-body">
                <ul>
                  <li><a href="profile.html" class="thumbnail"><img src="img/user.png" alt=""></a></li>
                  <li><a href="profile.html" class="thumbnail"><img src="img/user.png" alt=""></a></li>
                  <li><a href="profile.html" class="thumbnail"><img src="img/user.png" alt=""></a></li>
                  <li><a href="profile.html" class="thumbnail"><img src="img/user.png" alt=""></a></li>
                  <li><a href="profile.html" class="thumbnail"><img src="img/user.png" alt=""></a></li>
                  <li><a href="profile.html" class="thumbnail"><img src="img/user.png" alt=""></a></li>
                  <li><a href="profile.html" class="thumbnail"><img src="img/user.png" alt=""></a></li>
                  <li><a href="profile.html" class="thumbnail"><img src="img/user.png" alt=""></a></li>
                  <li><a href="profile.html" class="thumbnail"><img src="img/user.png" alt=""></a></li>
                </ul>
                <div class="clearfix"></div>
                <a class="btn btn-primary" href="#">View All Friends</a>
              </div>
            </div>
            <div class="panel panel-default groups">
              <div class="panel-heading">
                <h3 class="panel-title">Latest Groups</h3>
              </div>
              <div class="panel-body">
                <div class="group-item">
                  <img src="img/group.png" alt="">
                  <h4><a href="#" class="">Sample Group One</a></h4>
                  <p>This is a paragraph of intro text, or whatever I want to call it.</p>
                </div>
                <div class="clearfix"></div>
                <div class="group-item">
                  <img src="img/group.png" alt="">
                  <h4><a href="#" class="">Sample Group Two</a></h4>
                  <p>This is a paragraph of intro text, or whatever I want to call it.</p>
                </div>
                <div class="clearfix"></div>
                <div class="group-item">
                  <img src="img/group.png" alt="">
                  <h4><a href="#" class="">Sample Group Three</a></h4>
                  <p>This is a paragraph of intro text, or whatever I want to call it.</p>
                </div>
                <div class="clearfix"></div>
                <a href="#" class="btn btn-primary">View All Groups</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <footer>
      <div class="container">
        <p>Availabook Copyright &copy, 2017</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="js/bootstrap.js"></script>
    <script src="js/ekko-lightbox.js"></script>
    <script>
      $(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
      event.preventDefault();
      $(this).ekkoLightbox();
      }); 
      $(function () {
      $('[data-hover="tooltip"]').tooltip()
      })
    </script>
  </body>
</html>